import { Transaction } from "./finance-utils";

// Aghron Capital — Wealthtech Enterprise (Mumbai)
// 50 transactions: Nov 2025 – May 2026
// Revenue: Management Fees (AUM-based), Advisory Fees (HNI), Platform Fees (institutional)
// Expenses: Payroll, Infrastructure (AWS/Azure/GCP), Compliance (E&Y, SEBI), Legal, Marketing, Office, SaaS, Training, Travel

export const SAMPLE_TRANSACTIONS: Transaction[] = [
  // ─── November 2025 ──────────────────────────────────────────────────────────
  {
    date: "2025-11-01",
    type: "Revenue",
    amount: 520000,
    category: "Management Fees",
    description: "Stellar Growth Fund — AUM-based management fee, Nov (₹62Cr AUM)",
    vendor: "Stellar Growth Fund",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2025-11-05",
    type: "Revenue",
    amount: 360000,
    category: "Advisory Fees",
    description: "Mehta HNI Family Office — Portfolio review & restructuring advisory",
    vendor: "Mehta HNI Family Office",
    method: "RTGS",
    risk: "Low",
  },
  {
    date: "2025-11-08",
    type: "Expense",
    amount: 235000,
    category: "Payroll",
    description: "Full team payroll — Nov 2025, 12 FTE",
    vendor: "Internal",
    method: "Internal",
    risk: "Low",
  },
  {
    date: "2025-11-12",
    type: "Revenue",
    amount: 410000,
    category: "Platform Fees",
    description: "WealthDesk Integration — Monthly SaaS license, 14 enterprise clients",
    vendor: "WealthDesk Integration",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2025-11-15",
    type: "Expense",
    amount: 88000,
    category: "Infrastructure",
    description: "Amazon Web Services — Compute + S3 + RDS, Nov 2025",
    vendor: "Amazon Web Services",
    method: "Card",
    risk: "Low",
  },
  {
    date: "2025-11-19",
    type: "Expense",
    amount: 48000,
    category: "SaaS Tools",
    description: "Salesforce — CRM enterprise license renewal",
    vendor: "Salesforce",
    method: "Card",
    risk: "Low",
  },
  {
    date: "2025-11-22",
    type: "Expense",
    amount: 42000,
    category: "Marketing",
    description: "Meta Ads — Performance brand campaigns, Nov",
    vendor: "Meta Ads",
    method: "Card",
    risk: "Low",
  },
  {
    date: "2025-11-27",
    type: "Expense",
    amount: 39000,
    category: "Legal",
    description: "Khaitan & Co — Regulatory filing support, Nov",
    vendor: "Khaitan & Co",
    method: "Cheque",
    risk: "Low",
  },

  // ─── December 2025 ──────────────────────────────────────────────────────────
  {
    date: "2025-12-02",
    type: "Revenue",
    amount: 680000,
    category: "Management Fees",
    description: "Aghron Capital — AUM-based management fee, Dec (₹76Cr AUM)",
    vendor: "Aghron Capital",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2025-12-06",
    type: "Expense",
    amount: 90000,
    category: "Infrastructure",
    description: "Microsoft Azure — Cloud infra + Cosmos DB, Dec 2025",
    vendor: "Microsoft Azure",
    method: "Card",
    risk: "Low",
  },
  {
    date: "2025-12-10",
    type: "Revenue",
    amount: 445000,
    category: "Platform Fees",
    description: "Zerodha Institutional — Platform license renewals Q4 2025",
    vendor: "Zerodha Institutional",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2025-12-15",
    type: "Expense",
    amount: 242000,
    category: "Payroll",
    description: "Full team payroll — Dec 2025, 13 FTE",
    vendor: "Internal",
    method: "Internal",
    risk: "Low",
  },
  {
    date: "2025-12-18",
    type: "Revenue",
    amount: 290000,
    category: "Advisory Fees",
    description: "Nandan Industries — Estate planning & succession advisory, Dec",
    vendor: "Nandan Industries",
    method: "RTGS",
    risk: "Low",
  },
  {
    date: "2025-12-22",
    type: "Expense",
    amount: 54000,
    category: "Office",
    description: "Regus Mumbai — Office co-working lease Q4 2025",
    vendor: "Regus",
    method: "Cheque",
    risk: "Low",
  },
  {
    date: "2025-12-28",
    type: "Expense",
    amount: 65000,
    category: "Compliance",
    description: "E&Y — Quarterly tax advisory & audit support, Q4 2025",
    vendor: "Ernst & Young",
    method: "Cheque",
    risk: "Low",
  },

  // ─── January 2026 ───────────────────────────────────────────────────────────
  {
    date: "2026-01-03",
    type: "Revenue",
    amount: 780000,
    category: "Management Fees",
    description: "Stellar Growth Fund — AUM-based management fee, Jan (₹86Cr AUM)",
    vendor: "Stellar Growth Fund",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2026-01-07",
    type: "Expense",
    amount: 98000,
    category: "Infrastructure",
    description: "Amazon Web Services — Cloud infra, Jan 2026",
    vendor: "Amazon Web Services",
    method: "Card",
    risk: "Low",
  },
  {
    date: "2026-01-10",
    type: "Revenue",
    amount: 540000,
    category: "Advisory Fees",
    description: "Mehta HNI Family Office — Tax planning advisory, 3 HNI clients",
    vendor: "Mehta HNI Family Office",
    method: "RTGS",
    risk: "Low",
  },
  {
    date: "2026-01-15",
    type: "Expense",
    amount: 248000,
    category: "Payroll",
    description: "Full team payroll + contractor — Jan 2026, 13 FTE",
    vendor: "Internal",
    method: "Internal",
    risk: "Low",
  },
  {
    date: "2026-01-20",
    type: "Revenue",
    amount: 395000,
    category: "Platform Fees",
    description: "WealthDesk Integration — Platform fees, Jan 2026, 16 clients",
    vendor: "WealthDesk Integration",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2026-01-24",
    type: "Expense",
    amount: 74000,
    category: "SaaS Tools",
    description: "Notion + Linear — Team productivity tools annual renewal",
    vendor: "Notion / Linear",
    method: "Card",
    risk: "Low",
  },
  {
    date: "2026-01-29",
    type: "Expense",
    amount: 40000,
    category: "Travel",
    description: "MakeMyTrip — Business travel, investor meetings, Jan",
    vendor: "MakeMyTrip",
    method: "Card",
    risk: "Low",
  },

  // ─── February 2026 ──────────────────────────────────────────────────────────
  {
    date: "2026-02-01",
    type: "Expense",
    amount: 115000,
    category: "Marketing",
    description: "Meta Ads — Growth campaign, Feb 2026",
    vendor: "Meta Ads",
    method: "Card",
    risk: "Low",
  },
  {
    date: "2026-02-05",
    type: "Revenue",
    amount: 850000,
    category: "Management Fees",
    description: "Aghron Capital — AUM-based management fee, Feb (₹94Cr AUM)",
    vendor: "Aghron Capital",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2026-02-10",
    type: "Expense",
    amount: 255000,
    category: "Payroll",
    description: "Full team payroll — Feb 2026, 14 FTE",
    vendor: "Internal",
    method: "Internal",
    risk: "Low",
  },
  {
    date: "2026-02-14",
    type: "Revenue",
    amount: 480000,
    category: "Advisory Fees",
    description: "Patel Family Office — Portfolio restructuring & rebalancing advisory",
    vendor: "Patel Family Office",
    method: "RTGS",
    risk: "Low",
  },
  {
    date: "2026-02-18",
    type: "Expense",
    amount: 95000,
    category: "Infrastructure",
    description: "Google Cloud — BigQuery + Cloud Storage, Feb 2026",
    vendor: "Google Cloud",
    method: "Card",
    risk: "Low",
  },
  {
    date: "2026-02-21",
    type: "Expense",
    amount: 67000,
    category: "Compliance",
    description: "SEBI Compliance — Regulatory filing fees, Feb 2026",
    vendor: "SEBI Compliance",
    method: "Cheque",
    risk: "Low",
  },
  {
    date: "2026-02-26",
    type: "Expense",
    amount: 50000,
    category: "Training",
    description: "Coursera for Business — Team upskilling, data analytics & compliance",
    vendor: "Coursera for Business",
    method: "Card",
    risk: "Low",
  },

  // ─── March 2026 ─────────────────────────────────────────────────────────────
  {
    date: "2026-03-01",
    type: "Revenue",
    amount: 940000,
    category: "Management Fees",
    description: "Stellar Growth Fund — AUM-based management fee, Mar (₹104Cr AUM)",
    vendor: "Stellar Growth Fund",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2026-03-05",
    type: "Expense",
    amount: 258000,
    category: "Payroll",
    description: "Full team payroll — Mar 2026, 14 FTE",
    vendor: "Internal",
    method: "Internal",
    risk: "Low",
  },
  {
    date: "2026-03-10",
    type: "Revenue",
    amount: 570000,
    category: "Platform Fees",
    description: "Zerodha Institutional — Platform license, Mar 2026, 18 clients",
    vendor: "Zerodha Institutional",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2026-03-14",
    type: "Expense",
    amount: 105000,
    category: "Infrastructure",
    description: "Amazon Web Services — Cloud infra + ML workloads, Mar 2026",
    vendor: "Amazon Web Services",
    method: "Card",
    risk: "Medium",
  },
  {
    date: "2026-03-18",
    type: "Revenue",
    amount: 445000,
    category: "Advisory Fees",
    description: "Nandan Industries — Succession planning & wealth structuring",
    vendor: "Nandan Industries",
    method: "RTGS",
    risk: "Low",
  },
  {
    date: "2026-03-22",
    type: "Expense",
    amount: 72000,
    category: "Compliance",
    description: "SEBI Compliance — SEBI annual inspection filing, FY26",
    vendor: "SEBI Compliance",
    method: "Cheque",
    risk: "Low",
  },
  {
    date: "2026-03-27",
    type: "Expense",
    amount: 44000,
    category: "Office",
    description: "Regus Mumbai — Office lease Q1 2026 renewal",
    vendor: "Regus",
    method: "Cheque",
    risk: "Low",
  },

  // ─── April 2026 ─────────────────────────────────────────────────────────────
  {
    date: "2026-04-02",
    type: "Revenue",
    amount: 1080000,
    category: "Management Fees",
    description: "Aghron Capital — AUM-based management fee, Apr (₹118Cr AUM)",
    vendor: "Aghron Capital",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2026-04-05",
    type: "Expense",
    amount: 268000,
    category: "Payroll",
    description: "Full team payroll — Apr 2026, 15 FTE",
    vendor: "Internal",
    method: "Internal",
    risk: "Low",
  },
  {
    date: "2026-04-08",
    type: "Revenue",
    amount: 615000,
    category: "Platform Fees",
    description: "WealthDesk Integration — Platform fees, Apr 2026, 20 clients",
    vendor: "WealthDesk Integration",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2026-04-11",
    type: "Expense",
    amount: 112000,
    category: "Infrastructure",
    description: "Amazon Web Services — Infra + API compute, Apr 2026",
    vendor: "Amazon Web Services",
    method: "Card",
    risk: "Low",
  },
  {
    date: "2026-04-15",
    type: "Revenue",
    amount: 420000,
    category: "Advisory Fees",
    description: "Mehta HNI Family Office — Q2 2026 advisory retainer",
    vendor: "Mehta HNI Family Office",
    method: "RTGS",
    risk: "Low",
  },
  {
    date: "2026-04-18",
    type: "Expense",
    amount: 128000,
    category: "Marketing",
    description: "Google Ads — Growth campaign + brand search, Apr 2026",
    vendor: "Google Ads",
    method: "Card",
    risk: "Low",
  },
  {
    date: "2026-04-22",
    type: "Revenue",
    amount: 305000,
    category: "Advisory Fees",
    description: "Kapoor Ventures — New client onboarding advisory fee",
    vendor: "Kapoor Ventures",
    method: "RTGS",
    risk: "Low",
  },
  {
    date: "2026-04-25",
    type: "Expense",
    amount: 92000,
    category: "Compliance",
    description: "AZB & Partners — Contract review, new vendor agreements",
    vendor: "AZB & Partners",
    method: "Cheque",
    risk: "Low",
  },

  // ─── May 2026 ───────────────────────────────────────────────────────────────
  {
    date: "2026-05-01",
    type: "Revenue",
    amount: 1240000,
    category: "Management Fees",
    description: "Stellar Growth Fund — AUM-based management fee, May (₹136Cr AUM)",
    vendor: "Stellar Growth Fund",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2026-05-05",
    type: "Expense",
    amount: 285000,
    category: "Payroll",
    description: "Full team payroll — May 2026, 16 FTE",
    vendor: "Internal",
    method: "Internal",
    risk: "Low",
  },
  {
    date: "2026-05-08",
    type: "Revenue",
    amount: 680000,
    category: "Platform Fees",
    description: "Zerodha Institutional — Platform fees, May 2026, 22 enterprise clients",
    vendor: "Zerodha Institutional",
    method: "NEFT",
    risk: "Low",
  },
  {
    date: "2026-05-12",
    type: "Expense",
    amount: 122000,
    category: "Infrastructure",
    description: "Microsoft Azure — AI model hosting + Cosmos DB surge, May 2026",
    vendor: "Microsoft Azure",
    method: "Card",
    risk: "Medium",
  },
  {
    date: "2026-05-15",
    type: "Revenue",
    amount: 520000,
    category: "Advisory Fees",
    description: "Patel Family Office — Portfolio rebalancing, AIF structuring advisory",
    vendor: "Patel Family Office",
    method: "RTGS",
    risk: "Low",
  },
  {
    date: "2026-05-19",
    type: "Expense",
    amount: 78000,
    category: "Compliance",
    description: "E&Y — GSTR-3B audit readiness & TDS compliance review, Q1 FY27",
    vendor: "Ernst & Young",
    method: "Cheque",
    risk: "Low",
  },
  {
    date: "2026-05-23",
    type: "Expense",
    amount: 62000,
    category: "Legal",
    description: "Khaitan & Co — Fund documentation & SEBI registration renewal",
    vendor: "Khaitan & Co",
    method: "Cheque",
    risk: "Low",
  },
];
