/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ReconcileRouteImport } from './routes/reconcile'
import { Route as QueryRouteImport } from './routes/query'
import { Route as MonthlyRouteImport } from './routes/monthly'
import { Route as ModuleHealthRouteImport } from './routes/module-health'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as BoardPackageRouteImport } from './routes/board-package'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconcileRoute = ReconcileRouteImport.update({
  id: '/reconcile',
  path: '/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyRoute = MonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleHealthRoute = ModuleHealthRouteImport.update({
  id: '/module-health',
  path: '/module-health',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardPackageRoute = BoardPackageRouteImport.update({
  id: '/board-package',
  path: '/board-package',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board-package': typeof BoardPackageRoute
  '/brief': typeof BriefRoute
  '/categories': typeof CategoriesRoute
  '/compliance': typeof ComplianceRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/invoices': typeof InvoicesRoute
  '/module-health': typeof ModuleHealthRoute
  '/monthly': typeof MonthlyRoute
  '/query': typeof QueryRoute
  '/reconcile': typeof ReconcileRoute
  '/research': typeof ResearchRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/transactions': typeof TransactionsRoute
  '/treasury': typeof TreasuryRoute
  '/vendors': typeof VendorsRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/': typeof AgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board-package': typeof BoardPackageRoute
  '/brief': typeof BriefRoute
  '/categories': typeof CategoriesRoute
  '/compliance': typeof ComplianceRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/invoices': typeof InvoicesRoute
  '/module-health': typeof ModuleHealthRoute
  '/monthly': typeof MonthlyRoute
  '/query': typeof QueryRoute
  '/reconcile': typeof ReconcileRoute
  '/research': typeof ResearchRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/transactions': typeof TransactionsRoute
  '/treasury': typeof TreasuryRoute
  '/vendors': typeof VendorsRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents': typeof AgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board-package': typeof BoardPackageRoute
  '/brief': typeof BriefRoute
  '/categories': typeof CategoriesRoute
  '/compliance': typeof ComplianceRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/invoices': typeof InvoicesRoute
  '/module-health': typeof ModuleHealthRoute
  '/monthly': typeof MonthlyRoute
  '/query': typeof QueryRoute
  '/reconcile': typeof ReconcileRoute
  '/research': typeof ResearchRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/transactions': typeof TransactionsRoute
  '/treasury': typeof TreasuryRoute
  '/vendors': typeof VendorsRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/': typeof AgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board-package'
    | '/brief'
    | '/categories'
    | '/compliance'
    | '/daily'
    | '/dashboard'
    | '/health'
    | '/history'
    | '/invoices'
    | '/module-health'
    | '/monthly'
    | '/query'
    | '/reconcile'
    | '/research'
    | '/scenarios'
    | '/settings'
    | '/signals'
    | '/transactions'
    | '/treasury'
    | '/vendors'
    | '/workflows'
    | '/agents/$agentId'
    | '/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board-package'
    | '/brief'
    | '/categories'
    | '/compliance'
    | '/daily'
    | '/dashboard'
    | '/health'
    | '/history'
    | '/invoices'
    | '/module-health'
    | '/monthly'
    | '/query'
    | '/reconcile'
    | '/research'
    | '/scenarios'
    | '/settings'
    | '/signals'
    | '/transactions'
    | '/treasury'
    | '/vendors'
    | '/workflows'
    | '/agents/$agentId'
    | '/agents'
  id:
    | '__root__'
    | '/'
    | '/board-package'
    | '/brief'
    | '/categories'
    | '/compliance'
    | '/daily'
    | '/dashboard'
    | '/health'
    | '/history'
    | '/invoices'
    | '/module-health'
    | '/monthly'
    | '/query'
    | '/reconcile'
    | '/research'
    | '/scenarios'
    | '/settings'
    | '/signals'
    | '/transactions'
    | '/treasury'
    | '/vendors'
    | '/workflows'
    | '/agents/$agentId'
    | '/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardPackageRoute: typeof BoardPackageRoute
  BriefRoute: typeof BriefRoute
  CategoriesRoute: typeof CategoriesRoute
  ComplianceRoute: typeof ComplianceRoute
  DailyRoute: typeof DailyRoute
  DashboardRoute: typeof DashboardRoute
  HealthRoute: typeof HealthRoute
  HistoryRoute: typeof HistoryRoute
  InvoicesRoute: typeof InvoicesRoute
  ModuleHealthRoute: typeof ModuleHealthRoute
  MonthlyRoute: typeof MonthlyRoute
  QueryRoute: typeof QueryRoute
  ReconcileRoute: typeof ReconcileRoute
  ResearchRoute: typeof ResearchRoute
  ScenariosRoute: typeof ScenariosRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
  TransactionsRoute: typeof TransactionsRoute
  TreasuryRoute: typeof TreasuryRoute
  VendorsRoute: typeof VendorsRoute
  WorkflowsRoute: typeof WorkflowsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconcile': {
      id: '/reconcile'
      path: '/reconcile'
      fullPath: '/reconcile'
      preLoaderRoute: typeof ReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly': {
      id: '/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof MonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module-health': {
      id: '/module-health'
      path: '/module-health'
      fullPath: '/module-health'
      preLoaderRoute: typeof ModuleHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-package': {
      id: '/board-package'
      path: '/board-package'
      fullPath: '/board-package'
      preLoaderRoute: typeof BoardPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardPackageRoute: BoardPackageRoute,
  BriefRoute: BriefRoute,
  CategoriesRoute: CategoriesRoute,
  ComplianceRoute: ComplianceRoute,
  DailyRoute: DailyRoute,
  DashboardRoute: DashboardRoute,
  HealthRoute: HealthRoute,
  HistoryRoute: HistoryRoute,
  InvoicesRoute: InvoicesRoute,
  ModuleHealthRoute: ModuleHealthRoute,
  MonthlyRoute: MonthlyRoute,
  QueryRoute: QueryRoute,
  ReconcileRoute: ReconcileRoute,
  ResearchRoute: ResearchRoute,
  ScenariosRoute: ScenariosRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
  TransactionsRoute: TransactionsRoute,
  TreasuryRoute: TreasuryRoute,
  VendorsRoute: VendorsRoute,
  WorkflowsRoute: WorkflowsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
